[package]
name = "zenoh-hammer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = { version = "0.20" }
egui_extras = { version = "0.20" }
eframe = { version = "0.20", default-features = false, features = [ "persistence", "wgpu", "serde" ] }
tracing-subscriber = "0.3"
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh" }
async-std = { version = "=1.12", default-features = false }
futures = "0.3"
flume = "0.10"
strum = "0.24"
strum_macros = "0.24"
serde = "1.0"
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"

