[package]
name = "zenoh-hammer"
version = "0.4.0"
edition = "2021"

[[example]]
name = "hex_viewer"
path = "examples/hex_viewer.rs"

[profile.release-lto]
inherits = "release"
lto = true

[dependencies]
eframe = { version = "0.22", default-features = false, features = [ "persistence", "wgpu" ] }
egui_extras = { version = "0.22" }
egui_file = "0.10"
egui_dnd = "0.4"
tracing-subscriber = "0.3"
zenoh = { version = "0.10.0-rc", features = [ "default", "unstable" ] }
async-std = { version = "=1.12.0", default-features = false }
futures = "0.3.26"
flume = "0.11.0"
strum = "0.25"
strum_macros = "0.25"
serde = "1.0"
serde_json = "1.0"
env_logger = "0.10"
uhlc = "0.5"
uuid = "1.2"
arboard = "3.2"
include-cargo-toml = "0.1"
image = { version = "0.24", default-features = false, features = [ "png", "jpeg" ] }
