[package]
name = "zenoh-hammer"
version = "0.2.2"
edition = "2021"

[[example]]
name = "hex_viewer"
path = "examples/hex_viewer.rs"

[dependencies]
egui = { version = "0.21" }
egui_extras = { version = "0.21" }
eframe = { version = "0.21", default-features = false, features = [ "persistence", "wgpu", "serde" ] }
egui_file = "0.8"
tracing-subscriber = "0.3"
#zenoh = { version = "0.7.0-rc", features = [ "default", "unstable" ] }
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh.git", branch = "master", features = [ "default", "unstable" ] }
#zenoh = { git = "https://github.com/sanri/zenoh.git", branch = "master", features = [ "default", "unstable" ] }
async-std = { version = "=1.12", default-features = false }
futures = "0.3"
flume = "0.10"
strum = "0.24"
strum_macros = "0.24"
serde = "1.0"
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
uhlc = "0.5"
uuid = "1.2"
arboard = "3.2"
